import { ConnectButton } from "@rainbow-me/rainbowkit";
import { SignMessage } from "components/Sign";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Wagmi Dapp</title>
        <meta name="description" content="Generated by create next wagmi dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ConnectButton />
        <SignMessage />
      </div>
    </div>
  );
};

export default Home;
